//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cv.Models.Entiity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbCvEntities : DbContext
    {
        public DbCvEntities()
            : base("name=DbCvEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblAducation> tblAducation { get; set; }
        public virtual DbSet<tblAward> tblAward { get; set; }
        public virtual DbSet<tblExperience> tblExperience { get; set; }
        public virtual DbSet<tblInterest> tblInterest { get; set; }
        public virtual DbSet<tblSkills> tblSkills { get; set; }
        public virtual DbSet<tblAbout> tblAbout { get; set; }
    }
}
