//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cv.Models.Entiity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAducation
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string SubTitle { get; set; }
        public string Departmet { get; set; }
        public Nullable<decimal> Gpa { get; set; }
    }
}
