//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cv.Models.Entiity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAward
    {
        public int Id { get; set; }
        public string Award { get; set; }
    }
}
